In [2]:
import tensorflow as tf
import numpy as np

In [3]:
print(tf.add(1,2))
print(tf.add([1,2], [3,4]))
print(tf.square(5))
print(tf.reduce_sum([1,2,3]))

print(tf.square(2) + tf.square(3))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(13, shape=(), dtype=int32)


In [6]:
x = tf.matmul([[1]], [[2,3]])
print(x)
print(x.shape)
print(x.dtype)

tf.Tensor([[2 3]], shape=(1, 2), dtype=int32)
(1, 2)
<dtype: 'int32'>


In [7]:
ndarray  = np.ones([3,3])
tensor = tf.multiply(ndarray, 42)
print(tensor)

print(np.add(tensor, 1))

print(tensor.numpy())

tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [9]:
x = tf.random.uniform([3,3])

print(tf.test.is_gpu_available())

print(x.device.endswith('GPU:0'))

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
True
True


In [13]:
# 텐서플로 연산은 tf.device을 사용하여 특정한 장치에 명시적으로 배치가 가능함

import time

def time_matmul(x):
  start = time.time()
  for loop in range(10):
    tf.matmul(x, x)

  result = time.time() - start
  print('10 loops: {:0.2f}ms'.format(1000 * result))

print('On CPU:')
with tf.device('CPU:0'):
  x = tf.random.uniform([1000, 1000])
  assert x.device.endswith('CPU:0')
  time_matmul(x)

if tf.config.list_physical_devices("GPU"):
  print("On GPU:")
  with tf.device('GPU:0'):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith('GPU:0')
    time_matmul(x)

On CPU:
10 loops: 339.12ms
On GPU:
10 loops: 2.05ms


In [14]:
# 소스 데이터셋 생성

ds_tensors = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6])

import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
  Line 2
  Line 3
  """)

  ds_file = tf.data.TextLineDataset(filename)

In [15]:
# 변환 적용

ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)
ds_file = ds_file.batch(2)

In [17]:
# 반복

print('ds_tensors 요소')
for x in ds_tensors:
  print(x)

print('\nds_file 요소')
for x in ds_file:
  print(x)

ds_tensors 요소
tf.Tensor([4 1], shape=(2,), dtype=int32)
tf.Tensor([16  9], shape=(2,), dtype=int32)
tf.Tensor([36 25], shape=(2,), dtype=int32)

ds_file 요소
tf.Tensor([b'Line 1' b'  Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'  Line 3' b'  '], shape=(2,), dtype=string)
